
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class FormDiskon extends javax.swing.JFrame {

    /**
     * Creates new form FormDiskon
     */
    public FormDiskon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hargaAsliLabel = new javax.swing.JLabel();
        persenLabel = new javax.swing.JLabel();
        hargaSetelahDiskonLabel = new javax.swing.JLabel();
        hargaAsliTxt = new javax.swing.JTextField();
        hargaSetelahDiskonTxt = new javax.swing.JTextField();
        diskonCmb = new javax.swing.JComboBox<>();
        hitungBtn = new javax.swing.JButton();
        hematLbl = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();
        riwayatSP = new javax.swing.JScrollPane();
        riwayatTxtArea = new javax.swing.JTextArea();
        Tittle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hargaAsliLabel.setText("Harga Asli");

        persenLabel.setText("Persentase Diskon");

        hargaSetelahDiskonLabel.setText("Harga Setelah Diskon");

        hargaAsliTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hargaAsliTxtKeyTyped(evt);
            }
        });

        hargaSetelahDiskonTxt.setEditable(false);

        diskonCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "5%", "10%", "15%", "20%", "25%", "30%", "50%" }));
        diskonCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                diskonCmbItemStateChanged(evt);
            }
        });

        hitungBtn.setText("HITUNG");
        hitungBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungBtnActionPerformed(evt);
            }
        });

        hematLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        riwayatTxtArea.setColumns(20);
        riwayatTxtArea.setRows(5);
        riwayatSP.setViewportView(riwayatTxtArea);

        scrollPane1.add(riwayatSP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hematLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hargaAsliLabel)
                            .addComponent(hargaSetelahDiskonLabel)
                            .addComponent(persenLabel))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hitungBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(hargaAsliTxt)
                            .addComponent(hargaSetelahDiskonTxt)
                            .addComponent(diskonCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(scrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaAsliLabel)
                    .addComponent(hargaAsliTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(persenLabel)
                    .addComponent(diskonCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaSetelahDiskonLabel)
                    .addComponent(hargaSetelahDiskonTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(hitungBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hematLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Tittle.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        Tittle.setText("Aplikasi Perhitungan Diskon");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tittle)
                        .addGap(0, 177, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(Tittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hitungBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungBtnActionPerformed
        try {
        // Ambil nilai harga asli
        double hargaAsli = Double.parseDouble(hargaAsliTxt.getText());
        
        // Ambil persentase diskon dari JComboBox
        String diskonStr = (String) diskonCmb.getSelectedItem();
        int diskonPersen = Integer.parseInt(diskonStr.replace("%", ""));
        
        // Hitung jumlah diskon
        double jumlahDiskon = (hargaAsli * diskonPersen) / 100;
        
        // Hitung harga setelah diskon
        double hargaAkhir = hargaAsli - jumlahDiskon;
        
        // Tampilkan hasil di JTextField dan JLabel
        hargaSetelahDiskonTxt.setText(String.format("%.2f", hargaAkhir));
        hematLbl.setText("Anda menghemat: Rp " + String.format("%.2f", jumlahDiskon));
        
         // Simpan riwayat perhitungan
        String riwayat = "Harga Asli: Rp " + hargaAsliTxt.getText() +
                         ", Diskon: " + diskonCmb.getSelectedItem() +
                         ", Harga Setelah Diskon: Rp " + hargaSetelahDiskonTxt.getText() + "\n";

           // Pastikan riwayat tidak kosong sebelum menambahkan
        if (riwayatTxtArea.getText().isEmpty()) {
            riwayatTxtArea.setText(riwayat);
        } else {
            riwayatTxtArea.append(riwayat);
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan harga yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_hitungBtnActionPerformed

    private void diskonCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_diskonCmbItemStateChanged
        
    }//GEN-LAST:event_diskonCmbItemStateChanged

    private void hargaAsliTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargaAsliTxtKeyTyped
        char karakter = evt.getKeyChar();
        if (!Character.isDigit(karakter) && karakter != '.') {
            evt.consume(); // Hanya angka dan titik yang bisa dimasukkan
        }
    }//GEN-LAST:event_hargaAsliTxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDiskon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tittle;
    private javax.swing.JComboBox<String> diskonCmb;
    private javax.swing.JLabel hargaAsliLabel;
    private javax.swing.JTextField hargaAsliTxt;
    private javax.swing.JLabel hargaSetelahDiskonLabel;
    private javax.swing.JTextField hargaSetelahDiskonTxt;
    private javax.swing.JLabel hematLbl;
    private javax.swing.JButton hitungBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel persenLabel;
    private javax.swing.JScrollPane riwayatSP;
    private javax.swing.JTextArea riwayatTxtArea;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
